---

- name: Restart squid
  ansible.builtin.service:
    name: "squid"
    state: restarted

- name: "Set correct context"
  ansible.builtin.command: restorecon -R {{ squid_cache_dir2["path"] }} # noqa: no-changed-when
