---

- name: Restart squid
  ansible.builtin.service:
    name: "squid"
    state: restarted

- name: Restart squid3
  ansible.builtin.service:
    name: "squid3"
    state: restarted

- name: "Set correct context"
  ansible.builtin.command: restorecon -R {{ squid_cache_dir2["path"] }}
